### PR TITLE
Esc to single selection

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Fantastic thank you!

**Comment by Piterden** [comment]
Don't know would it works without https://github.com/anomalylabs/editor-field_type/pull/20

**Comment by RyanThompson** [comment]
Why do we need duplicate inputs for #20? Is there any way to do without that?

**Comment by Piterden** [comment]
It seems, data attributes are making conflicts and causing incorrect mode definitions

**Comment by RyanThompson** [comment]
Can we change those instead of the multiple inputs? I would much rather correct that. Two inputs scares me :-P

**Comment by Piterden** [comment]
We could use not a textarea for data-holder element. But Codemirror should invokes on clear element.

**Comment by RyanThompson** [comment]
Ok, let’s put the data on a wrapper perhaps.

**Comment by Piterden** [comment]
`.codemirror` you mean ?

**Comment by RyanThompson** [comment]
Lemme fool around with it - I see what you’re doing there.

Also please try and keep PRs separated by feature - I think some bled together there.

**Comment by Piterden** [comment]
Here is only one feature. But prev - multimode made some other features enabled by default.

**Comment by Piterden** [comment]
So, how is your progress?

**Comment by RyanThompson** [comment]
Didn’t get a chance to mess with it. Later today likely.

**Pull request merged**
