### PR TITLE
CodeMirror

### PR DESCRIPTION
**Pull request by Piterden**
Just list of dropped for now.

### CODE REVIEW

**Comment by RyanThompson** [comment]
What is this?

**Comment by RyanThompson** [comment]
If this is an upload thing - I think we should use a button / icon similar to the fullscreen icon.

**Comment by Piterden** [comment]
Yeah? Why just not load in place like there, on GitHub?

**Comment by Piterden** [comment]
I can show window, which you had told about, by dropped file validation pass.

**Comment by RyanThompson** [comment]
Ya drop a vid / screen of this if you would - before I review.

**Comment by Piterden** [comment]
Sure moment

**Comment by Piterden** [comment]
editor

**Comment by Piterden** [comment]
### Updated.
Now it supports a folder upload, force deleting, pasting a tag to the editor.
@RyanThompson Seems time for quick test.

ezgif-3-59809804da

**Comment by RyanThompson** [comment]
I've gotten this done ^_^

**Comment by Piterden** [comment]
How can I check it?

**Comment by RyanThompson** [comment]
LOL Oh sorry fuckin Im in the wrong place

**Comment by RyanThompson** [comment]
Change your composer.json to include `~2.2.0`

**Comment by Piterden** [comment]
Maybe there are another places, where I should increase version?

**Comment by RyanThompson** [comment]
"anomaly/editor-field_type": "~2.2.0",

Just run twig:clear and asset:clear probably? If it’s sticking a bit.

**Comment by Piterden** [comment]
Ya, thanks a lot. It's clear. How about other addons?

**Comment by RyanThompson** [comment]
I’d say just bounce it off me in a feature request issue before you write too much - if it’s quicker for you just slack me or something too

But if it’s a bigger thing - github issue for a feature request will let me point others to it and get their thoughts on it too.

**Pull request closed without merging**
